import React, {useState} from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import {
  Button
} from "@material-ui/core"

export default function Home() {
  const [randLink, setRandLink] = useState<string>("") 
  const [ButtonText, setButtonText] = useState<string>("Click to Go") 


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          AtCoder RandomPick
        </h1>

        <div className={styles.grid}>
          <Button variant = "outlined" size = "large" onClick = {() => {setRandLink(pick())}}>
            <Link href = {randLink}>
              <a target = "_blank">
                {ButtonText}
              </a>  
            </Link>
          </Button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://Arisahyper.com"
          target="_blank"
        >
          (c) 2021 Arisahyper.com 
        </a>
      </footer>
    </div>
  )
}

const pick = () => {
			let num:    number = Math.floor(Math.random() * 206) + 1;
			let numstr: string = ('000' + String(num)).slice( -3 );
			let link:   string = "https://atcoder.jp/contests/abc" + numstr + "/tasks";
			
			return link;
}